//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteakHouseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chefe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chefe()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string AccountFaceBook { get; set; }
        public string AccountTwitter { get; set; }
        public string AccountGmail { get; set; }
        public string Description { get; set; }
        public Nullable<int> Food_Id { get; set; }
    
        public virtual Food Food { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
    }
}
